### ISSUE TITLE
Keyerror on validation for stage 3

### ISSUE THREAD

**Issue by cmauget** [Chat-3D/Chat-3D#12]
Hello,

First of all thank you for your amazing work. I am trying to evaluate chat 3d on conversation tasks (hence why I haven't switched to v2).
However, when trying stage 3 training (or inference for that matter) I always get a KeyError on the valoader. Is it expected behavior?

Thank you in advance for your time and consideration.

**Comment by ZzZZCHS** [comment]
Hi, thanks for your interest. Could you provide the details of the KeyError?

**Comment by cmauget** [comment]
Thank you for your answer.

I followed the README file and installed all the dependencies on a clean docker.

Stage 1 and 2 run without issues, as well as the first part of stage 3. However, when the program tries to compute validation metrics, I get the following KeyError:

```
2024-03-25T12:57:46 | dataset.dataloader: MetaLoader has 1 dataloaders, 1036 batches in total
dataloader index=0 name=point_cloud, batch-size=1 length(#batches)=1036 
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/workspace/Chat-3D/tasks/train.py", line 392, in <module>
    main(cfg)
  File "/workspace/Chat-3D/tasks/train.py", line 338, in main
    global_step = train(
  File "/workspace/Chat-3D/tasks/train.py", line 118, in train
    val_metrics = evaluate(model, model_without_ddp, val_loaders, epoch, global_step, device, config,
  File "/workspace/Chat-3D/tasks/train.py", line 170, in evaluate
    for i, (media_type, batch) in tqdm(enumerate(val_loader)):
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/workspace/Chat-3D/dataset/dataloader.py", line 55, in __iter__
    batch = next(_iter)
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 240, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/workspace/Chat-3D/dataset/dataset_val.py", line 33, in __getitem__
    scene_id, obj_id, target_id, scene_feat, scene_attr = self.get_anno(index)
  File "/workspace/Chat-3D/dataset/base_dataset.py", line 26, in get_anno
    scene_id = self.anno[index]["scene_id"]
KeyError: 121

0it [00:00, ?it/s]

Traceback (most recent call last):
  File "/workspace/Chat-3D/tasks/train.py", line 392, in <module>
Traceback (most recent call last):
  File "/workspace/Chat-3D/tasks/train.py", line 392, in <module>
    main(cfg)
  File "/workspace/Chat-3D/tasks/train.py", line 338, in main
    global_step = train(
      File "/workspace/Chat-3D/tasks/train.py", line 118, in train
main(cfg)
  File "/workspace/Chat-3D/tasks/train.py", line 338, in main
    val_metrics = evaluate(model, model_without_ddp, val_loaders, epoch, global_step, device, config,
  File "/workspace/Chat-3D/tasks/train.py", line 170, in evaluate
        global_step = train(for i, (media_type, batch) in tqdm(enumerate(val_loader)):

  File "/workspace/Chat-3D/tasks/train.py", line 118, in train
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    val_metrics = evaluate(model, model_without_ddp, val_loaders, epoch, global_step, device, config,
  File "/workspace/Chat-3D/tasks/train.py", line 170, in evaluate
    for i, (media_type, batch) in tqdm(enumerate(val_loader)):
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/workspace/Chat-3D/dataset/dataloader.py", line 55, in __iter__
    batch = next(_iter)
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    for obj in iterable:
  File "/workspace/Chat-3D/dataset/dataloader.py", line 55, in __iter__
    batch = next(_iter)
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    data = self._next_data()
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    return self._process_data(data)
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    data.reraise()
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 240, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/workspace/Chat-3D/dataset/dataset_val.py", line 33, in __getitem__
    scene_id, obj_id, target_id, scene_feat, scene_attr = self.get_anno(index)
  File "/workspace/Chat-3D/dataset/base_dataset.py", line 26, in get_anno
    scene_id = self.anno[index]["scene_id"]
KeyError: 1190

    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 240, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/workspace/Chat-3D/dataset/dataset_val.py", line 33, in __getitem__
    scene_id, obj_id, target_id, scene_feat, scene_attr = self.get_anno(index)
  File "/workspace/Chat-3D/dataset/base_dataset.py", line 26, in get_anno
    scene_id = self.anno[index]["scene_id"]
KeyError: 535

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 726305) of binary: /opt/conda/envs/chat-3d/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/chat-3d/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.1', 'console_scripts', 'torchrun')())
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/chat-3d/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tasks/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-03-2
  host      : 
  rank      : 1 (local_rank: 1)
  exitcode  : 1 
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-03-25
  host      : 
  rank      : 2 (local_rank: 2)
  exitcode  : 1
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-25
  host      :
  rank      : 0 (local_rank: 0)
  exitcode  : 1 
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

On a side note:  
- pycocoevalcap is not in the requirements.txt and needs to be installed separately.
- There is an error in the run.sh script. `,lr:` needs to be added at ligne 21 to be able to define the learnng rate using the `--lr` argument. The current ligne is `ARGS=$(getopt -o "s:p:e:" -l "stage:,pretrained_path:,evaluate:" -- "$@")` whereas it should be `ARGS=$(getopt -o "s:p:e:" -l "stage:,pretrained_path:,evaluate:,lr:" -- "$@")`

**Comment by ZzZZCHS** [comment]
I know why it happens... The `self.annos` here is assumed to be a list, but the [current anno files](https://github.com/Chat-3D/Chat-3D/blob/main/scripts/config.py#L80-L91) (`annotations/scanrefer_val_conversation.json` & `annotations/scanrefer_val_detail.json`) for validation in stage 3 do not satisfy this. This was a mistake in a recent [commit](https://github.com/Chat-3D/Chat-3D/commit/d9cb31ed53468ce6e9569f0a78ef3cd448210f5b#diff-e9ffa9c36082d5a0b2ae4098b1b77d020a8d57d159bc89255fcad17287bc3ed9R84). Changing it back to `scanrefer_val_stage3.json` would solve this problem (or modify `scanrefer_val_conversation.json` &  `scanrefer_val_detail.json` to the same format as `scanrefer_val_stage3.json`).

Thanks for your note. It's my fault that I didn't double-check these released codes. Sorry for the inconvenience.

**Comment by cmauget** [comment]
Thank you, it works now.

I tried to modify the `scanrefer_val_conversation.json` & `scanrefer_val_detail.json` to the same format as `scanrefer_val_stage3.json`, but there is no object ID in those.

In the run.sh script, a value is needed for '--evaluate', contrary to what is given in README file. Adding `::` instead of `:` after 'evaluate' would solve this issue, so line 21 gives you:

`ARGS=$(getopt -o "s:p:e::" -l "stage:,pretrained_path:,evaluate::,lr:" -- "$@")`

You should also modify line 35 to:

```
-e | --evaluate)
     evaluate=true
     shift 2
     ;;
```

Thank you for your time, and I am glad I could help.

**Comment by ZzZZCHS** [comment]
The keys in `scanrefer_val_conversation.json` are in the format of `{scene_id}_{obj_id}`. For example, "scene0011_00_1" denotes that the scene_id is "scene0011_00" and the obj_id is "1".

And thanks again for your detailed notes!

**Comment by ZzZZCHS** [comment]
I've update the [run.sh](https://github.com/Chat-3D/Chat-3D/blob/main/scripts/run.sh#L20-L43) by removing the `getopt` options and modifying the while loop. I hope it should work properly now. Thank you for your help~

**Comment by cmauget** [comment]
Thank you, everything is working now. Here is a small script if needed to change the annotations to the desired format:

    import json
    
    def modify_json(input_file, output_file):
        with open(input_file, 'r') as f:
            data = json.load(f)
    
        modified_data = []
        for scene_id, qa_pairs in data.items():
            split = scene_id.split('_')
            scene_id_short = split[0] + '_' + split[1]  # Extracting scene ID without the last part
            for qa_pair in qa_pairs:
                question = qa_pair["Question"]
                answer = qa_pair['Answer']
                modified_data.append({
                    "scene_id": scene_id_short,
                    "obj_id": split[2],
                    "Question": question,
                    "Answer": answer
                })
    
        with open(output_file, 'w') as f:
            json.dump(modified_data, f, indent=4)
    
    if __name__ == "__main__":
        modify_json("scanrefer_val_conversation.json", "scanrefer_val_conversation_new.json")
        modify_json("scanrefer_val_detail.json", "scanrefer_val_detail_new.json")
